# Generated by Django 3.2.6 on 2021-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='movie_people',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_people',
            field=models.ManyToManyField(through='movies.MoviePeople', to='movies.People'),
        ),
    ]
