version: '3'
services:
  pg_db:
    restart: always
    environment:
      - POSTGRES_PASSWORD=yandex01
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies
    build:
      context: .
      dockerfile: ./schema_design/Dockerfile
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  django_app:
    command: >
      sh -c "python manage.py migrate admin &&
             python manage.py migrate auth &&
             python manage.py migrate contenttypes &&
             python manage.py migrate sessions &&
             python manage.py migrate movies --fake &&
             python manage.py createsuperuser --noinput &&
             python load_data.py &&
             rm db.sqlite &&
             rm load_data.py &&
             gunicorn --bind :8000 --workers 2 config.wsgi:application"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DJANGO_SECRET_KEY=somesecretkeyishere
      - DJANGO_SUPERUSER_USERNAME=simenshteyn
      - DJANGO_SUPERUSER_EMAIL=simenshteyn@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=simenshteyn
      - ALLOWED_HOSTS=127.0.0.1
      - DB_HOST=pg_db
      - DB_PASSWORD=yandex01
      - DB_USER=postgres
      - DB_NAME=movies
    build:
      context: .
      dockerfile: ./movies_admin/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pg_db
