version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./movies_admin/Dockerfile
    ports:
      - "8000:8000"
  db:
    build:
      context: .
      dockerfile: ./schema_design/Dockerfile
    ports:
      - "5432:5432"
